apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  labels:
    app: geonode
    component: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geonode
      component: celery
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: geonode
        component: celery
    spec:
      imagePullSecrets:
      - name: registrykey
      containers:
        - args:
            - celery-cmd
          command:
            - /usr/src/geonode/entrypoint-celery.sh
          envFrom:
            - configMapRef:
                name: geonode--env
          image: registry.kan.com.ar/kan/geoexpressportal/geonode-cloud:4.2.4.0-01
          imagePullPolicy: IfNotPresent
          name: celery4geonode
          resources:
            requests:
              memory: "2Gi"
              cpu: "400m"
            limits:
              cpu: "1000m"
              memory: "8Gi"
          volumeMounts:
            - mountPath: /mnt/volumes/statics
              name: statics
            - mountPath: /tmp
              name: tmp
      volumes:
        - name: statics
          persistentVolumeClaim:
            claimName: statics
        - name: tmp
          persistentVolumeClaim:
            claimName: tmp
status: {}
