apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: geonode
    component: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geonode
      component: django
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: geonode
        component: django
    spec:
      imagePullSecrets:
      - name: registrykey
      containers:
        - args:
            - uwsgi
            - --ini
            - /usr/src/geonode/uwsgi.ini
          command:
            - /usr/src/geonode/entrypoint.sh
          envFrom:
            - configMapRef:
                name: geonode--env
          image: kantit/geonode-cloud-core:1.0.0-rc01
          imagePullPolicy: IfNotPresent
          name: django4geonode
          resources:
            requests:
              memory: "2Gi"
              cpu: "400m"
            limits:
              cpu: "1000m"
              memory: "8Gi"
          volumeMounts:
            - mountPath: /mnt/volumes/statics
              name: statics
            - mountPath: /tmp
              name: tmp
      volumes:
        - name: statics
          persistentVolumeClaim:
            claimName: statics
        - name: tmp
          persistentVolumeClaim:
            claimName: tmp
status: {}
