apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapstore
  labels:
    app: geonode
    component: mapstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geonode
      component: mapstore
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: geonode
        component: mapstore
    spec:
      imagePullSecrets:
      - name: registrykey
      containers:
        - workingDir: /geonode-mapstore-client/geonode_mapstore_client/client
          image: registry.kan.com.ar/kan/geoexpressportal/geonode-mapstore-client:4.2.0.0-cmd
          imagePullPolicy: IfNotPresent
          name: mapstore4geonode
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              cpu: "400m"
              memory: "2Gi"
status: {}