apiVersion: v1
kind: PersistentVolume
metadata:
  name: statics-pv
  labels:
    name: statics-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp3
