apiVersion: v1
kind: Service
metadata:
  name: gndatabase
  labels:
    component: gndatabase
spec:
  selector:
    component: gndatabase
  ports:
    - protocol: TCP
      port: 5432
  type: ClusterIP  # Servicio interno accesible dentro del clúster