apiVersion: v1
kind: Service
metadata:
  name: gndatabase
  labels:
    component: gndatabase
spec:
  selector:
    component: gndatabase
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30007
