apiVersion: v1
kind: Service
metadata:
  name: gndatabase
  namespace: KUBERNETES-NAMESPACE
  labels:
    component: gndatabase
spec:
  selector:
    component: gndatabase
  ports:
    - protocol: TCP
      port: 5432