---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: statics-django
  namespace: default
  labels:
    app: geonode
    type: statics-django
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: gp3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tmp-django
  namespace: default
  labels:
    app: geonode
    type: tmp-files-django
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: gp3
