apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: KUBERNETES-NAMESPACE
  labels:
    app: geonode
    type: statics
  name: statics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: gp3
