apiVersion: v1
kind: Service
metadata:
  name: celery
  namespace: KUBERNETES-NAMESPACE
  labels:
    component: celery
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    component: celery
