apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: KUBERNETES-NAMESPACE
  labels:
    component: django
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    component: django
