apiVersion: v1
kind: Service
metadata:
  name: mapstore
  namespace: KUBERNETES-NAMESPACE
  labels:
    component: mapstore
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    component: mapstore
