apiVersion: v1
kind: Service
metadata:
  namespace: KUBERNETES-NAMESPACE
  name: redis
  labels:
    component: redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    component: redis
