apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: rabbitmq
    type: data
  name: rabbitmq-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage
  selector:
    matchLabels:
      name: rabbitmq-data-pv
status: {}
