apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi  # Cambiado a 8Gi para mejor almacenamiento en producción
  storageClassName: gp2  # StorageClass estándar de AWS para EBS