apiVersion: v1
kind: Service
metadata:
  name: acl
  namespace: KUBERNETES-NAMESPACE
  labels:
    component: acl
spec:
  selector:
    component: acl
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
status:
  loadBalancer: {}
