apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: KUBERNETES-NAMESPACE
  labels:
    component: rabbitmq
spec:
  selector:
    component: rabbitmq
  ports:
  - name: "5672"
    port: 5672
    targetPort: 5672
  - name: "15672"
    port: 15672
    targetPort: 15672
status:
  loadBalancer: {}
