apiVersion: v1
kind: Service
metadata:
  name: wcs
  namespace: KUBERNETES-NAMESPACE
  labels:
    component: wcs
spec:
  selector:
    component: wcs
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "8081"
    port: 8081
    targetPort: 8081
status:
  loadBalancer: {}
