apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: KUBERNETES-NAMESPACE
  labels:
    component: webui
spec:
  selector:
    component: webui
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "8081"
    port: 8081
    targetPort: 8081
status:
  loadBalancer: {}
