apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gwc
    type: data
  name: geowebcache-data
  namespace: KUBERNETES-NAMESPACE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage
  selector:
    matchLabels:
      name: geowebcache-data-pv

