apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapstore
  namespace: KUBERNETES-NAMESPACE
  labels:
    app: geonode
    component: mapstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geonode
      component: mapstore
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: geonode
        component: mapstore
    spec:
      imagePullSecrets:
      - name: registrykey
      containers:
        - image: kantit/geonode-cloud-mapstore-client:1.0.0-rc1
          imagePullPolicy: IfNotPresent
          name: mapstore4geonode
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              cpu: "400m"
              memory: "2Gi"
          volumeMounts:
            - name: statics
              mountPath: /usr/share/nginx/html/
            - name: mapstore-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: http-js
              mountPath: /etc/nginx/http.js
              subPath: http.js
      volumes:
        - name: statics
          persistentVolumeClaim:
            claimName: statics
        - name: mapstore-conf
          configMap:
            name: mapstore-conf
            items:
            - key: default.conf
              path: default.conf
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
            - key: nginx.conf
              path: nginx.conf
        - name: http-js
          configMap:
            name: http-js
            items:
            - key: http.js
              path: http.js
status: {}