apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: KUBERNETES-NAMESPACE
  labels:
    app: geonode
    component: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geonode
      component: memcached
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: geonode
        component: memcached
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - |
              memcached ${MEMCACHED_OPTIONS}
          envFrom:
            - configMapRef:
                name: geonode--env
          image: memcached:alpine
          imagePullPolicy: IfNotPresent
          name: memcached4geonode
          resources:
            requests:
              memory: "1Gi"
              cpu: "400m"
            limits:
              cpu: "1000m"
              memory: "8Gi"
status: {}
