apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: rabbitmq
    type: data
  name: rabbitmq-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: gp3  # Cambiar a clase de almacenamiento EKS