apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
  namespace: KUBERNETES-NAMESPACE
  labels:
    app: geoserver
    component: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoserver
      component: rest
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: geoserver
        component: rest
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              key: JAVA_OPTS
              name: geoserver--env
        - name: RABBITMQ_PORT_5672_TCP
          valueFrom:
            configMapKeyRef:
              key: RABBITMQ_PORT_5672_TCP
              name: geoserver--env
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              key: RABBITMQ_PORT
              name: geoserver--env
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              key: SPRING_PROFILES_ACTIVE
              name: geoserver--env
        image: geoservercloud/geoserver-cloud-rest:1.9-SNAPSHOT
        imagePullPolicy: "IfNotPresent"
        name: rest
        resources:
          requests:
            memory: "1Gi"
            cpu: "200m"
          limits:
            cpu: "1500m"
            memory: "2Gi"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: jndi
          mountPath: "/etc/geoserver/jndi.yml"
          subPath: "jndi.yaml"
        - name: geoserver
          mountPath: "/etc/geoserver/geoserver.yml"
          subPath: "geoserver.yaml"
        - name: statics
          mountPath: /mnt/volumes/statics
        - name: plugins
          mountPath: /opt/app/bin/BOOT-INF/lib/
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: jndi
        configMap:
          name: jndi-configmap
      - name: geoserver
        configMap:
          name: geoserver-configmap
      - name: statics
        persistentVolumeClaim:
          claimName: statics
      - name: plugins
        persistentVolumeClaim:
          claimName: plugins
status: {}