apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbdata-pv
  namespace: KUBERNETES-NAMESPACE
  labels:
    name: dbdata-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: KUBERNETES-VOL-DIR/dbdata
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - KUBERNETES-NODE-NAME