apiVersion: v1
kind: Service
metadata:
  namespace: KUBERNETES-NAMESPACE
  name: mapstore
  labels:
    component: mapstore
spec:
  selector:
    component: mapstore
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081