apiVersion: v1
kind: Service
metadata:
  namespace: KUBERNETES-NAMESPACE
  name: memcached
  labels:
    component: memcached
spec:
  ports:
    - name: "11211"
      port: 11211
      targetPort: 11211
  selector:
    component: memcached