apiVersion: v1
kind: Service
metadata:
  name: wfs
  labels:
    component: wfs
spec:
  selector:
    component: wfs
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "8081"
    port: 8081
    targetPort: 8081
  type: ClusterIP