apiVersion: apps/v1
kind: Deployment
metadata:
  name: wfs
  labels:
    app: geoserver
    component: wfs
    ogc: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoserver
      component: wfs
      ogc: service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: geoserver
        component: wfs
        ogc: service
    spec:
      containers:
      - env:
        - name: RABBITMQ_PORT_5672_TCP
          valueFrom:
            configMapKeyRef:
              key: RABBITMQ_PORT_5672_TCP
              name: geoserver--env
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              key: RABBITMQ_PORT
              name: geoserver--env
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              key: SPRING_PROFILES_ACTIVE
              name: geoserver--env
        image: geoservercloud/geoserver-cloud-wfs:1.8.10
        imagePullPolicy: "IfNotPresent"
        name: wfs
        resources:
          requests:
            memory: "1Gi"
            cpu: "200m"
          limits:
            cpu: "4000m"
            memory: "2Gi"
        volumeMounts:
        - name: jndi
          mountPath: "/etc/geoserver/jndi.yml"
          subPath: "jndi.yaml"
        - name: geoserver
          mountPath: "/etc/geoserver/geoserver.yml"
          subPath: "geoserver.yaml"
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: jndi
        configMap:
          name: jndi-configmap
      - name: geoserver
        configMap:
          name: geoserver-configmap
status: {}
