apiVersion: v1
kind: Service
metadata:
  name: acl
  labels:
    component: acl
spec:
  selector:
    component: acl
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  type: LoadBalancer  # Se agrega el tipo LoadBalancer para que sea accesible desde fuera del clúster
status:
  loadBalancer: {}