apiVersion: v1
kind: Service
metadata:
  name: gwc
  labels:
    component: gwc
spec:
  selector:
    component: gwc
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "8081"
    port: 8081
    targetPort: 8081
  type: LoadBalancer  # Configuración para acceso externo
status:
  loadBalancer: {}