apiVersion: v1
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  GEONODE_DATABASE: geonode
  GEONODE_DATABASE_PASSWORD: geonode
  GEONODE_GEODATABASE: geonode_data
  GEONODE_GEODATABASE_PASSWORD: geonode_data
  GEONODE_DATABASE_SCHEMA: public
  GEONODE_GEODATABASE_SCHEMA: public
  DATABASE_HOST: gndatabase
  DATABASE_PORT: "5432"
  DATABASE_URL: postgis://geonode:geonode@gndatabase:5432/geonode
  GEODATABASE_URL: postgis://geonode_data:geonode_data@gndatabase:5432/geonode_data
  GEONODE_DB_CONN_MAX_AGE: "0"
  GEONODE_DB_CONN_TOUT: "5"
  DEFAULT_BACKEND_DATASTORE: datastore
  BROKER_URL: amqp://guest:guest@rabbitmq:5672/
  CELERY_BEAT_SCHEDULER: celery.beat:PersistentScheduler
  ASYNC_SIGNALS: "True"

  SITEURL: https://KUBERNETES-SITE-URL/

  # PostgreSQL
  POSTGRESQL_MAX_CONNECTIONS: "200"

kind: ConfigMap
metadata:
  name: gndatabase--env
  namespace: KUBERNETES-NAMESPACE